---
title: "Install RPy2 in ArcGIS Pro Environment"
output: html_notebook
---



# Clone Existing ArcGIS Pro `conda` Environment
*Note:* ArcGIS Pro Python "clone environment" functionality is broken as of ~2.3.x. Use this workaround until ESRI fixes it. 

The default ESRI Python environment `arcgispro_py3` environment cannot be edited on computers with limited user rights since it is installed in `C:\Program Files\`. Therefore, this environment has to be "cloned" and changes made to the clone. 

The default ArcGIS Pro environment must be used as it contains all of the required "ESRI stuff"" to work correctly in Pro. To clone the default`arcgispro_py3` environment, open a command prompt and navigate to the Scripts folder in `C:\Program Files\ArcGIS\Pro\bin\Python`. The Scripts directory is where conda commands can be executed.

```
cd  C:\Program Files\ArcGIS\Pro\bin\Python\Scripts
```

From this directory, conda will be used to activate the root environment.

```
activate root
```

Finally, this environment will be cloned. By default this environment will be stored in the local users AppData/ESRI directory. With this environment, other environments can be created and new libraries tested. This environemnt will only be available for the user and will be stored in `C:\Users\<your username>\AppData\Local\ESRI\conda\envs\`

```
conda create -n arcgispro_py3_clone --clone arcgispro-py3
```

To use this environment, it must be activated. Use the following command to activate. 

```
activate my_arcgispro_clone
```

# Install required r packages
Install R packages from the default Anaconda channel. 

```
conda install tzlocal
```

# Set ArcGIS Pro to use this environment
Open ArcGIS Pro, Settings, Python, Manage Environments and select the newly cloned environment. 

