---
title: "Stream Planform Dimensions"
output: html_document
---

```{r}
library(arcgisbinding)
arc.check_product()
library(sp)
library(sf)
library(units)
# Source hydraulic geometry functions
source("//mvrdfs/egis/Work/Office/Regional/ERDC/EMRRP_Sediment/Methods/FluvialGeomorphr/HydraulicGeometry2.R")
    
```

```{r}
flowline_points_fc <- "//mvrdfs/egis/Work/Office/Regional/ERDC/EMRRP_Sediment/Senachwine/Data/Watershed/01_LowerSenachwineCreek/LowerSenachwineCreek.gdb/flowline_points"

valley_line_fc <- "//mvrdfs/egis/Work/Office/Regional/ERDC/EMRRP_Sediment/Senachwine/Data/Watershed/01_LowerSenachwineCreek/LowerSenachwineCreek.gdb/flowline_500"

# Import fc to sp
flowline_points <- arc2sp(flowline_points_fc)
valley_line     <- arc2sp(valley_line_fc)
    
# Convert to data frame
flowline_pts <- data.frame(flowline_points@data)
```

```{r}
# Convert sp to `sf` object
flowline_points_sf <- st_as_sf(flowline_points)
valley_line_sf     <- st_as_sf(valley_line)

# Calculate distance between flowline_points and valley_line and convert from
# meters (original coodinate system) to feet. 
flowline_points_sf$dist_vl <- drop_units(st_distance(flowline_points_sf, valley_line_sf)) * 3.28084
```

```{r}
plot(x = flowline_points_sf$POINT_M[1:100],    
     y = flowline_points_sf$dist_vl[1:100],
     type = "l")
```

```{r}
# Create test dataset
m <- seq(0,15,length.out=100)
test <- data.frame(POINT_M = m, 
                   dist_vl = abs(sin(m)))
plot(test$POINT_M, test$dist_vl, type="l")
```

```{r}
find_inflections <- function(data, vl_dist, rt_dist) {
  # Computes the m-value of the next and previous crossing points.
  #
  # Args:
  #    data:           data frame; Must contain fields: "POINT_M" that holds 
  #                    flowline route distance; "dist_vl" that holds the
  #                    distance from the flowline to the valley_line
  #    vl_dist:        numeric; the threshold distance that a `dist_vl` value
  #                    must be to be considered close enough to the flowline
  #                    to be considered an inflection point. 
  #    rt_dist:        numeric; 
  #
  # Returns:
  #    the `data` data frame with two new fields calculated: `prev_inf_m` and
  #    `next_inf_m`
    # Create new fields to hold the m values of the inflection points
    data$prev_inf_m <- 0
    data$next_inf_m <- 0
    # Iterate through rows of test and identify the previous and next    
    # inflection points
    for(i in 1:length(data$POINT_M)) {
        # Subset test for the current record
        t <- data[i,]
        ## Create a table of potential inflection points
        # dist values within 1.0 feet are considered a potential inflection
        # point
        inf <- data[data$dist_vl < vl_dist, c("POINT_M","dist_vl")]
        
        ## Find the next inflection point
        next_inflection_index <- which(inf$POINT_M >= t$POINT_M)[1]
        # Handle the end of the series
        if(is.na(next_inflection_index)) {
            next_inflection_index <- length(inf$POINT_M)
        } 
        # Find inflections close to this value
        next_m <- inf[next_inflection_index,]$POINT_M
        n_inf <- inf[inf$POINT_M > next_m - rt_dist & 
                     inf$POINT_M < next_m + rt_dist,]
        # Write the m value of the next inflection point
        data[i,]$next_inf_m <- n_inf[n_inf$dist_vl == 
                                     min(n_inf$dist_vl),]$POINT_M
        
        ## Find the previous inflection point
        prev_inflection_point <- length(which(inf$POINT_M <= t$POINT_M))
        # Find inflections close to this value
        prev_m <- inf[prev_inflection_point,]$POINT_M
        n_inf <- inf[inf$POINT_M > prev_m - rt_dist & 
                     inf$POINT_M < prev_m + rt_dist,]
        # Write the m value of the previous inflection point
        data[i,]$prev_inf_m <- n_inf[n_inf$dist == 
                                     min(n_inf$dist_vl),]$POINT_M
    }
    return(data)
}
```

```{r}
test2 <- find_inflections(data = test, vl_dist = 0.2, rt_dist = 1)
```

# Calculate inflections for real streams
```{r}
flowline_points_sf_inf <- find_inflections(data = flowline_points_sf[1:1000,],
                                           vl_dist = 1.0,
                                           rt_dist = 0.001)
```





